language: java

before_script:
  - >
      sudo apt install -y
      build-essential
      omniidl
      libomniorb4-dev
      libcos4-dev
      libomnithread3-dev
      libzmq3-dev
      libmysqlclient-dev
      ant
  - sudo apt install -y python python-pip
  - pip install --user Sphinx~=1.0 ipython~=5.0
script:
  - ant build package

addons:
  apt:
    update: true

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: "build/tango-${TRAVIS_BRANCH}.tar.gz"
    skip_cleanup: true
    on:
      tags: true
